(rule
 (target compcert.ini)
 (action
  (with-stdout-to
   compcert.ini
   (run %{bin:ini_creator}))))

(rule
 (target compcert.config)
 (action
  (with-stdout-to
   compcert.config
   (run %{bin:config_creator}))))

(install
 (files compcert.ini)
 (section share_root)
 (package compcert))

(env
 (_
  (binaries
   tools/ndfun.exe
   tools/modorder.exe
   tools/config_to_ml.exe
   tools/ini_creator.exe
   tools/config_creator.exe)))
